### PR TITLE
EBS mirgration

### PR DESCRIPTION
**Pull request by leakingtapan**
xref: kubernetes/kubernetes#70590

Tested that CSI Controller service is called for attach while in-tree driver is still used for CreateVolume.

There is a problem I found with following message:
```
I1031 23:24:06.158943       1 connection.go:239] GRPC error: rpc error: code = Internal desc = Could not get volume with ID "aws://us-east-2a/vol-0d3b8a174ebb7e16f": InvalidParameterValue: Value (aws://us-east-2a/vol-0d3b8a174ebb7e16f) for parameter volumes is invalid. Expected: 'vol-...'.
        status code: 400, request id: bd4680c1-3e16-40a4-88b2-573aec494c03
```

This is caused by EBS in-tree driver has a special volume naming convention while CSI driver expected a regular naming that starts with `vol-`.

I will debug more for the cause.

### CODE REVIEW

**Comment by leakingtapan** [comment]
@davidz627  @ddebroy

**Comment by leakingtapan** [comment]
Here is where the volumeName is generated: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2214

**Comment by leakingtapan** [comment]
Here is the PV:
```
>> kk describe pv
Name:              pvc-0c5325eb-dd62-11e8-8dc5-0203bf87cc1c
Labels:            failure-domain.beta.kubernetes.io/region=us-east-2
                   failure-domain.beta.kubernetes.io/zone=us-east-2a
Annotations:       kubernetes.io/createdby: aws-ebs-dynamic-provisioner
                   pv.kubernetes.io/bound-by-controller: yes
                   pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
Finalizers:        [kubernetes.io/pv-protection external-attacher/com-amazon-aws-csi-ebs]
StorageClass:      gp2
Status:            Bound
Claim:             default/claim1
Reclaim Policy:    Delete
Access Modes:      RWO
Capacity:          4Gi
Node Affinity:
  Required Terms:
    Term 0:        failure-domain.beta.kubernetes.io/zone in [us-east-2a]
                   failure-domain.beta.kubernetes.io/region in [us-east-2]
Message:
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://us-east-2a/vol-0d3b8a174ebb7e16f
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

I think this is because in-tree provisioner is still used. The problem should be gone once we start using CSI provisioner

**Comment by ddebroy** [comment]
LGTM so far!

**Comment by davidz627** [comment]
@leakingtapan were you able to test with pre-provisioned volumes successfully?

**Comment by leakingtapan** [comment]
Chatted offline on slack. I'm able to test pre-provisioned volumes with this change. So far I verified that attach succeeds on AWS after feature gate is turned on with `CSIMigration` and `CSIMigrationAWS` enabled. I confirmed  @davidz627 's concerns that `MountVolume` might fail and it is due to `volumeToMount.DevicePath` is populated with csi volumeattachment name instead of real path in `GenerateMountVolumeFunc`.

**Comment by davidz627** [comment]
very cool! Could you fix the presubmit failures? https://github.com/kubernetes/kubernetes/pull/70590#issuecomment-435463964

LGTM other than that

**Comment by leakingtapan** [comment]
The CSI devicePath issue is related to: kubernetes/kubernetes#70852

**Pull request closed without merging**
